baseurl = "http://www.marinin.pw/"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "ru"
layoutdir = "layouts"
publishdir = "public"
author = "Илья Маринин"
title = "Илья Маринин"
disqusshortname = ""
pluralizelisttitles = false
theme = "hugo-theme-crisp"

[blackfriday]
hrefTargetBlank = true

[params]
description = "Илья Маринин - блог о программировании"
dateform = "02.01.2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
logofile = "/img/logo.jpg"
lang = "ru"
disqus = "marinin-pw"
twitter="ilya_marinin"
hideReadingTime = true

[taxonomies]
  tag = "tags"